module.exports.ingredientsArray = ["Artichoke",
    "Arugula",
    "Asparagus",
    "Avocado",
    "Bamboo Shoots",
    "Bean Sprouts",
    "Beet",
    "Belgian Endive",
    "Bell Pepper",
    "Broccoli",
    "Brussels Sprouts",
    "Cabbage",
    "Calabash",
    "Capers",
    "Carrot",
    "Cauliflower",
    "Celery",
    "Celtuce",
    "Chayote",
    "Cucumber",
    "English Cucumber",
    "Gherkin",
    "Pickling Cucumbers",
    "Daikon Radish",
    "Edamame",
    "Elephant Garlic",
    "Endive",
    "Escarole",
    "Fennel",
    "Fiddlehead",
    "Galangal",
    "Garlic",
    "Ginger",
    "Grape Leaves",
    "Wax Beans",
    "Greens",
    "Beet Greens",
    "Collard Greens",
    "Dandelion Greens",
    "Kohlrabi Greens",
    "Mustard Greens",
    "Rapini",
    "Spinach",
    "Turnip Greens",
    "Hearts of Palm",
    "Horseradish",
    "Jícama",
    "Kale",
    "Curly",
    "Lacinato",
    "Ornamental",
    "Kohlrabi",
    "Leeks",
    "Lemongrass",
    "Lettuce",
    "Iceberg",
    "Romaine",
    "Lotus Root",
    "Lotus Seed",
    "Napa Cabbage",
    "Nopales",
    "Okra",
    "Olive",
    "Onion",
    "Parsley",
    "Parsley Root",
    "Parsnip",
    "Peas",
    "green peas",
    "snow peas",
    "sugar snap peas",
    "Plantain",
    "Potato",
    "Pumpkin",
    "Purslane",
    "Radicchio",
    "Radish",
    "Rutabaga",
    "Shallots",
    "Sweet Potato",
    "Swiss Chard",
    "Taro",
    "Tomatillo",
    "Tomato",
    "Turnip",
    "Water Chestnut",
    "Water Spinach",
    "Watercress",
    "Winter Melon",
    "Yams",
    "Zucchini",]